{"nbformat":4,"nbformat_minor":0,"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"colab":{"name":"983_m4_demo3_exception_handling_v1.0.ipynb","provenance":[],"collapsed_sections":[]}},"cells":[{"cell_type":"code","metadata":{"id":"n_WddHEehDMT","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":72},"outputId":"b51b61f7-a151-4fc2-ce40-291f5dac5cf5","executionInfo":{"status":"ok","timestamp":1591848642093,"user_tz":0,"elapsed":5257,"user":{"displayName":"Atin Gupta","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gi1LyLILoESCrCvqA94FJEzlaNfumYdJznKg_osrQ=s64","userId":"01235820350389977490"}}},"source":["try:\n","  x = float(input(\"Enter a number: \"))\n","  y = float(input(\"Enter another number: \"))\n","\n","  if (y==0):\n","    print(\"infinite\")\n","  else:\n","    z= x-y\n","    print(z)\n","except:\n","  print(\"Some error has ocuured\")"],"execution_count":16,"outputs":[{"output_type":"stream","text":["Enter a number: 123\n","Enter another number: 23\n","100.0\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"l7tAg-2PumQ9","colab_type":"text"},"source":["## Exception Handling"]},{"cell_type":"code","metadata":{"id":"fGNsGx6humRC","colab_type":"code","outputId":"83a55e20-e8b2-4574-a604-18f1967716f7","colab":{}},"source":["# Example 1\n","var1=10\n","var2=0\n","result=var1/var2   # We can't divide any number by Zero. In case it is done, it will throw ZeroDivisionError which is predefined exception\n","print(result)\n","print('end')"],"execution_count":0,"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"division by zero","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[1;32m<ipython-input-2-aa63a48c93eb>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0mvar1\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m10\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0mvar2\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m \u001b[0mresult\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mvar1\u001b[0m\u001b[1;33m/\u001b[0m\u001b[0mvar2\u001b[0m   \u001b[1;31m# We can't divide any number by Zero. In case it is done, it will throw ZeroDivisionError which is predefined exception\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      5\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mresult\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'end'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mZeroDivisionError\u001b[0m: division by zero"]}]},{"cell_type":"code","metadata":{"id":"AB-YQCNIumRp","colab_type":"code","outputId":"026d63ec-f685-498a-c550-cd23bd7f558e","colab":{}},"source":["# Example 2\n","list1=[1,2,3,4]\n","print(list1[len(list1)])   # This will give IndexError as we have tried to access an index which is beyond the range\n","print(list1[-6])           # This will also give IndexError as we have tried to access an index which is beyond the range"],"execution_count":0,"outputs":[{"output_type":"error","ename":"IndexError","evalue":"list index out of range","traceback":["\u001b[1;31m---------------------------------------------------------------------------\u001b[0m","\u001b[1;31mIndexError\u001b[0m                                Traceback (most recent call last)","\u001b[1;32m<ipython-input-6-76897246fea9>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# Example 2\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0mlist1\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m1\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;36m2\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;36m3\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;36m4\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 3\u001b[1;33m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlist1\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mlen\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlist1\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m   \u001b[1;31m# This will give IndexError as we have tried to access an index which is beyond the range\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      4\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mlist1\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;33m-\u001b[0m\u001b[1;36m6\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m)\u001b[0m           \u001b[1;31m# This will also give IndexError as we have tried to access an index which is beyond the range\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n","\u001b[1;31mIndexError\u001b[0m: list index out of range"]}]},{"cell_type":"code","metadata":{"id":"s1AOXXDIumSC","colab_type":"code","outputId":"1f305e59-d073-4cc1-a4b7-fd3c85b19175","colab":{}},"source":["# Example 3  -- Exception Handling\n","\n","try:\n","    var1=10\n","    var2=0\n","    result=var1/var2 # This line will raise Zero Division Error Exception and then Python will search for exception handler block i.e. except block\n","    print(result)\n","except:              # The except block will handle the exception and prints the messages\n","    print('Some exception Occured')\n","    print('End')  \n"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Some exception Occured\n","End\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"hmgZ01vJumSc","colab_type":"code","colab":{}},"source":["# Important Point :- Once the program flow comes out of try block and enters except block, it never goes back to try block\n"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"kYclrXrpumS4","colab_type":"code","outputId":"0a4cc9c8-0124-4e5c-b672-42a7658bce8e","colab":{"base_uri":"https://localhost:8080/","height":108},"executionInfo":{"status":"ok","timestamp":1591848903392,"user_tz":0,"elapsed":1066,"user":{"displayName":"Atin Gupta","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gi1LyLILoESCrCvqA94FJEzlaNfumYdJznKg_osrQ=s64","userId":"01235820350389977490"}}},"source":["# Example 4  -- Value Error Exception Example\n","\n","import sys\n","randomlist=['a',0,2]\n","for entry in randomlist:\n","    try:\n","        print(\"The entry is\",entry)\n","        r=1/int(entry)\n","        break\n","    except:\n","        print(\"Oops!\",sys.exc_info()[0],\"occured\")\n","        print(\"Next Entry\")\n","        print()\n","        print(\"The reciprocal of\",entry,\"is\",r)\n"],"execution_count":19,"outputs":[{"output_type":"stream","text":["The entry is a\n","Oops! <class 'ValueError'> occured\n","The entry is 0\n","Oops! <class 'ZeroDivisionError'> occured\n","The entry is 2\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"9-NcAFeEumTN","colab_type":"code","outputId":"32cd83fd-acf1-4869-f560-246a08019cf5","colab":{}},"source":["# Example 5  -- Only try block is not possible\n","try:\n","    var1=10\n","    var2=0\n","    result=var1/var2 # This line will raise Zero Division Error Exception and then Python will search for exception handler block i.e. except block\n","    print(result)\n"],"execution_count":0,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"unexpected EOF while parsing (<ipython-input-13-5ee81e60e121>, line 6)","traceback":["\u001b[1;36m  File \u001b[1;32m\"<ipython-input-13-5ee81e60e121>\"\u001b[1;36m, line \u001b[1;32m6\u001b[0m\n\u001b[1;33m    print(result)\u001b[0m\n\u001b[1;37m                 ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m unexpected EOF while parsing\n"]}]},{"cell_type":"markdown","metadata":{"id":"rZ9o68DoumTl","colab_type":"text"},"source":["## Try- Except-Else"]},{"cell_type":"code","metadata":{"id":"Sx9_c47rumTp","colab_type":"code","outputId":"fe5e95e6-9953-4a54-dd54-c092ddec79ee","colab":{}},"source":["# Example 6\n","try:\n","    var1=10\n","    var2=eval(input('Enter the divisor'))\n","    result=var1/var2\n","except:\n","    print('Some Exception Happened')\n","    print(sys.exc_info())\n","else:\n","    print('There was no exception')\n","\n","finally:\n","    print('End')\n"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Enter the divisor2\n","There was no exception\n","End\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"gHQcEoqnumUI","colab_type":"code","outputId":"00b6e8f7-abb7-4b73-a05d-81f23a6d4d6a","colab":{"base_uri":"https://localhost:8080/","height":90},"executionInfo":{"status":"ok","timestamp":1591849001872,"user_tz":0,"elapsed":2883,"user":{"displayName":"Atin Gupta","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gi1LyLILoESCrCvqA94FJEzlaNfumYdJznKg_osrQ=s64","userId":"01235820350389977490"}}},"source":["# Example 7\n","try:\n","    var1=10\n","    var2=eval(input('Enter the divisor'))\n","    result=var1/var2\n","except:\n","    print('Some Exception Happened')\n","    print(sys.exc_info())\n","else:\n","    print('There was no exception')\n","\n","finally:\n","    print('End')"],"execution_count":21,"outputs":[{"output_type":"stream","text":["Enter the divisora\n","Some Exception Happened\n","(<class 'NameError'>, NameError(\"name 'a' is not defined\",), <traceback object at 0x7f834297bb48>)\n","End\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"wgUW-wcrumUd","colab_type":"code","outputId":"7a48f88b-743f-4485-9ab3-cd9d49cfdf14","colab":{}},"source":["# Example 8 -- Multiple Except Blocks \n","try:\n","    var1=10\n","    var2=0\n","    list1=[1,2,3]\n","    list1[3]=var1/var2\n","    print(list1[3])\n","except ZeroDivisionError:\n","    print('Numbers cant be divided by zero')\n","except ValueError:\n","    print('It is a value error')\n","except IndexError:\n","    print('The index is out of range')\n","except:\n","    print(\"Some unknown error has occured\")    "],"execution_count":0,"outputs":[{"output_type":"stream","text":["Numbers cant be divided by zero\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"8hJtm0rCumU0","colab_type":"code","colab":{}},"source":["#In the above code, there are problems with ‘Index out of range’ and ‘Zero Division Error’. \n","#But, at a time only one exception is raised and here the expression for division executes first and Zero Division Error \n","#Exception is raised. Then the program flow enters the proper exception handler and prints the message. \n","#In case that is absent, the interpreter will print the exception message as it does without any except block\n"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"0K5nCOODumVI","colab_type":"code","outputId":"5580a6b9-67bc-45a7-f011-509bcfb3bb13","colab":{}},"source":["# Example 9 --  Multiple Except Blocks (Error Scenario)\n","# This program will throw error because except block must be written at last after writing all specific exception based except blocks. Except block can handle any exception\n","try:\n","    var1=10\n","    var2=0\n","    list1=[1,2,3]\n","    list1[3]=var1/var2\n","    print(list1[3])\n","except:\n","    print('Some Exception Occured')\n","    print(sys.exc_info())\n","except ZeroDivisionError:\n","    print('Numbers cant be divided by zero')\n","except ValueError:\n","    print('It is a value error')\n","except IndexError:\n","    print('The index is out of range')"],"execution_count":0,"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"default 'except:' must be last (<ipython-input-23-cb2e028ca986>, line 11)","traceback":["\u001b[1;36m  File \u001b[1;32m\"<ipython-input-23-cb2e028ca986>\"\u001b[1;36m, line \u001b[1;32m11\u001b[0m\n\u001b[1;33m    print(sys.exc_info())\u001b[0m\n\u001b[1;37m                       ^\u001b[0m\n\u001b[1;31mSyntaxError\u001b[0m\u001b[1;31m:\u001b[0m default 'except:' must be last\n"]}]},{"cell_type":"code","metadata":{"id":"KFDMiefFumVn","colab_type":"code","outputId":"36503720-fd9e-4215-f74c-91c93e002472","colab":{}},"source":["# Example 10 -- Multiple exception using tuple\n","\n","try:\n","    var1=10\n","    var2=0\n","    list1=[1,2,3]\n","    list1[3]=var1/var2\n","    print(list1[3])\n","\n","except (ValueError, IndexError):\n","    print('It is a value error')\n","except:\n","    print('Some Exception Occured')\n","    print(sys.exc_info())\n","    "],"execution_count":0,"outputs":[{"output_type":"stream","text":["Some Exception Occured\n","(<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x000001333FCDDD48>)\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"BM1OWrn1umV8","colab_type":"code","colab":{}},"source":["# Except block acts as a default handler and it can handle any exception. In case if we want to know the details of the handled exception, we can use this statement\n"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"5f1HInY1umWW","colab_type":"text"},"source":["## Finally Block"]},{"cell_type":"code","metadata":{"id":"RpxtkdLZumWa","colab_type":"code","colab":{}},"source":["# Example 11 -- try-except-finally block\n","\n","try:\n","    file_obj=open('test_file.txt','w')\n","    \n","    file_obj.write('Python is Awesome')\n","    \n","    #print(1/0)\n","\n","    #file.close()\n","\n","except:\n","    print('Some Exception Occured')\n","    print(sys.exc_info())\n","    \n","finally:\n","    file_obj.close()"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"hwbpUShuumW-","colab_type":"code","colab":{}},"source":["# This finally clause will execute no matter what and in this case closing the file is required. \n","#Due to this, the closing statement is written in finally clause. \n","#The Finally block is not a mandatory block to be written. \n","#There is only one finally bock possible unlike multiple except blocks.\n"],"execution_count":0,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"RzSOVZUwumXS","colab_type":"text"},"source":["## Exception Propagation"]},{"cell_type":"code","metadata":{"id":"B_pFvKRiumXV","colab_type":"code","outputId":"e81b40a8-3f50-47b3-f6af-47dbd4d91845","colab":{"base_uri":"https://localhost:8080/","height":108},"executionInfo":{"status":"ok","timestamp":1591849465344,"user_tz":0,"elapsed":898,"user":{"displayName":"Atin Gupta","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14Gi1LyLILoESCrCvqA94FJEzlaNfumYdJznKg_osrQ=s64","userId":"01235820350389977490"}}},"source":["# Example 12 -- Exception propagation 1st Example\n","# In this case, Key Error Exception has been raised in method2. As there is no handler present in method2, the exception has been propagated to calling method i.e. method1 and gets handled there\n","\n","class Test:\n","    def __init__(self):\n","        try:\n","            print(\"Welcome to init method\")\n","            raise ZeroDivisionError\n","        except:\n","            print(\"some exception occured\")\n","        finally:\n","            print(\"I will always execute\")\n","    def method1(self):\n","        try:\n","            self.method2()\n","        except:\n","            print(\"Exception handled\")\n","    \n","    def method2(self,):\n","        print(\"welcome to method2\")\n","        raise KeyError\n","\n","try:\n","  Test().method1()\n","except:\n","    print(\"Error\")"],"execution_count":25,"outputs":[{"output_type":"stream","text":["Welcome to init method\n","some exception occured\n","I will always execute\n","welcome to method2\n","Exception handled\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"7ht7X6jIumXo","colab_type":"code","outputId":"480b2f73-d5bd-490e-e357-37b92e69b079","colab":{}},"source":["# Example 13 -- Exception Proapagation 2nd Example\n","\n","class Test:\n","    def __init__(self):\n","        try:\n","            print(\"Welcome to init method\")\n","            raise ZeroDivisionError\n","        except:\n","            print(\"some exception occured\")\n","        finally:\n","            print(\"I will always execute\")\n","    def method1(self):\n","        try:\n","            self.method2()\n","        except:\n","            print(\"Exception handled\")\n","            raise ZeroDivisionError\n","    \n","    def method2(self,):\n","        print(\"welcome to method2\")\n","        raise KeyError\n","try:\n","    Test().method1()\n","except:\n","    print(\"handled outside\")\n","finally:\n","    print(\"it executes finally\")"],"execution_count":0,"outputs":[{"output_type":"stream","text":["Welcome to init method\n","some exception occured\n","I will always execute\n","welcome to method2\n","Exception handled\n","handled outside\n","it executes finally\n"],"name":"stdout"}]},{"cell_type":"markdown","metadata":{"id":"8FeAo3fUumYI","colab_type":"text"},"source":[""]},{"cell_type":"code","metadata":{"id":"DKnal7LVumYN","colab_type":"code","colab":{}},"source":[""],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"ItUNB_o9umY5","colab_type":"code","colab":{}},"source":[""],"execution_count":0,"outputs":[]}]}